services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # Porta do protocolo AMQP
      - "15672:15672"   # Porta da interface web (management)
    environment:
      RABBITMQ_DEFAULT_USER: yan
      RABBITMQ_DEFAULT_PASS: yan
    hostname: sd-rabbit
    restart: unless-stopped
