spring.application.name=eleicao

spring.datasource.url=jdbc:h2:mem:collectdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

spring.rabbitmq.host= 172.20.15.106
spring.rabbitmq.username=yan
spring.rabbitmq.password=yan
