services:
  postgres:
    image: postgres:latest
    container_name: bd_sd_eleicao
    restart: always
    environment:
      POSTGRES_DB: eleicao
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
